[[cors]]
allowed_origins = "*"
allowed_methods = ["GET", "POST"]
allowed_headers = "*"

[[headers]]
for = ["**/*.woff2", "**/*.woff", "**/*.svg", "**/*.ttf", "**/*.otf", "**/*.eot", "**/*.js", "**/*.css"]
compress = "gzip"
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[headers]]
for = ["**/*.png", "**/*.jpg", "**/*.jpeg", "**/*.gif", "**/*.webp"]
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[redirects]]
from = "/degrowth/polls/index.html"
to = "/degrowth/degrowth-is-popular/"

[[redirects]]
from = "/to-ignore-for-now/organizations/index.html"
to = "/admin/organizations/"

[[redirects]]
from = "/transformative-learning/index.html"
to = "/resources/transformative-learning/"

[[redirects]]
from = "/how-to-fight-establishment-propaganda-and-win/index.html"
to = "/guides/how-to-fight-establishment-propaganda-and-win/"

[[redirects]]
from = "/transformative-learning/our-tl-for-degrowth-principles/principle-1/index.html"
to = "/resources/transformative-learning/our-tl-for-degrowth-principles/principle-1/"

[[redirects]]
from = "/how-to-get-your-dissident-ideas-heard/index.html"
to = "/guides/how-to-get-your-dissident-ideas-heard/"

[[redirects]]
from = "/agenda/archives/index.html"
to = "/admin/agenda/archives/"

[[redirects]]
from = "/to-ignore-for-now/sitemap/index.html"
to = "/admin/sitemap/"

[[redirects]]
from = "/organizations/index.html"
to = "/admin/organizations/"

[[redirects]]
from = "/team/editors/index.html"
to = "/admin/team/editors/"

[[redirects]]
from = "/transformative-learning/activity-1/index.html"
to = "/resources/transformative-learning/our-tl-for-degrowth-principles/principle-1/activity-1/"

[[redirects]]
from = "/to-ignore-for-now/agenda/archives/index.html"
to = "/admin/agenda/archives/"

[[redirects]]
from = "/sitemap/index.html"
to = "/admin/sitemap/"

[[redirects]]
from = "/to-ignore-for-now/team/editors/index.html"
to = "/admin/team/editors/"

[[redirects]]
from = "/about/how-to-help/index.html"
to = "/about/how-you-can-help/"

[[redirects]]
from = "/media/magazine/index.html"
to = "/media/magazines/"

[[redirects]]
from = "/to-ignore-for-now/posts/index.html"
to = "/admin/posts/"

[[redirects]]
from = "/to-ignore-for-now/legal-terms/index.html"
to = "/admin/legal-terms/"

[[redirects]]
from = "/a-degrowth-economy-explained/index.html"
to = "/degrowth/a-degrowth-economy-explained/"

[[redirects]]
from = "/about/transparency/index.html"
to = "/about/ai-transparency/"

[[redirects]]
from = "/resources/degrowth-101/index.html"
to = "/resources/degrowth-for-businesses/"

[[redirects]]
from = "/to-ignore-for-now/agenda/index.html"
to = "/admin/agenda/"

[[redirects]]
from = "/degrowth/how-do-we-pay-for-it/index.html"
to = "/degrowth/how-do-we-pay-for-degrowth/"

[[redirects]]
from = "/privacy-policy/index.html"
to = "/admin/privacy-policy/"

[[redirects]]
from = "/to-ignore-for-now/accessibility/index.html"
to = "/admin/accessibility/"

[[redirects]]
from = "/activity-1/index.html"
to = "/resources/transformative-learning/our-tl-for-degrowth-principles/principle-1/activity-1/"

[[redirects]]
from = "/transformative-learning/glossary-of-transformative-learning-for-degrowth/index.html"
to = "/resources/transformative-learning/glossary-of-transformative-learning-for-degrowth/"

[[redirects]]
from = "/accessibility/index.html"
to = "/admin/accessibility/"

[[redirects]]
from = "/degrowth/misconceptions-about-degrowth/index.html"
to = "/degrowth/myth-and-misconceptions/"

[[redirects]]
from = "/our-tl-for-degrowth-principles/index.html"
to = "/resources/transformative-learning/our-tl-for-degrowth-principles/"

[[redirects]]
from = "/how-to-help/index.html"
to = "/about/how-you-can-help/"

[[redirects]]
from = "/degrowth-games/index.html"
to = "/resources/degrowth-games/"

[[redirects]]
from = "/team/index.html"
to = "/admin/team/"

[[redirects]]
from = "/who/index.html"
to = "/about/who/"

[[redirects]]
from = "/transformative-learning/our-tl-for-degrowth-principles/principle-1/activity-1/index.html"
to = "/resources/transformative-learning/our-tl-for-degrowth-principles/principle-1/activity-1/"

[[redirects]]
from = "/values-principles/index.html"
to = "/degrowth/values-principles/"

[[redirects]]
from = "/to-ignore-for-now/team/index.html"
to = "/admin/team/"

[[redirects]]
from = "/media/videos-1/index.html"
to = "/media/videos/"

[[redirects]]
from = "/polls/index.html"
to = "/degrowth/degrowth-is-popular/"

[[redirects]]
from = "/legal-terms/index.html"
to = "/admin/legal-terms/"

[[redirects]]
from = "/posts/index.html"
to = "/admin/posts/"

[[redirects]]
from = "/transformative-learning/our-tl-for-degrowth-principles/index.html"
to = "/resources/transformative-learning/our-tl-for-degrowth-principles/"

[[redirects]]
from = "/to-ignore-for-now/privacy-policy/index.html"
to = "/admin/privacy-policy/"

